[project]
name = "sclerr"
version = "0.1.4"
description = "Strips garbage from c++ linker errors"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = []

[project.scripts]
sclerr = "sclerr:main"

[tool.uv]
package = true