[project]
name = "slinkerr"
version = "0.1.0"
description = "Strips garbage from c++ linker errors"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = []

[project.scripts]
slinkerr = "slinkerr:main"